version: v1.0
name: EC2 deployment
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: Deploy
    task:
      secrets:
        # Mount the secret:
        - name: typerek-semaphore-private-key
      prologue:
        commands:
          # Correct premissions since they are too open by default:
          - chmod 0600 ~/.keys/*
          # Add the key to the ssh agent:
          - ssh-add ~/.keys/*
          - checkout
      jobs:
      - name: Deploy
        commands:
          - echo 'Deploying to production!'
          - checkout master
          - bundle install --path vendor/bundle
          - bundle exec cap production deploy